### PR TITLE
Add option to hide event items, but show which days have them.

### PR DESCRIPTION
**Pull request by angelicochris**
For our use case we actually didn't want the events themselves to show on the calendar, but to have a background color on the days themselves that had events and on clicking the day the events would be revealed in a list below the calendar. This adds that option using the boolean prop showEvents and the class hasEvent added to days that have a least one event.

If there is a better way to go about this I'd appreciate the feedback as I am still learning Vue.

I also updated the packages through an audit to fix any vulnerabilities.

### CODE REVIEW

**Comment by angelicochris** [comment]
Should hasEvent also be conditioned on if showEvents is false?

**Comment by SwithFr** [comment]
Hi, nice feature ! don't need it in my case but you should create your PR on the original [repo](https://github.com/richardtallent/vue-simple-calendar)

**Comment by angelicochris** [comment]
I would, but I actually need the part you added as well so my PR would end up including your changes which you already have a PR for.

**Comment by SwithFr** [comment]
My bad ! I didn't realize. 

PR accepted ;)

**Pull request merged**
